Add new observation form for custom observations
Georiviere/Georiviere-public pull request #70
Opened 2024-04-24 13:08 UTC by Bo-Duke

2024-05-13 08:19 UTC, dtrucs commented on src/api/stations.ts
> +  }
```suggestion
  const station = await fetchStation(id);
  if (!station) {
    return null;
  };
  const observations = await fetchStationObservations(id);
  return {
   ...station,
   observations,
  };
```
Or Promise.all the queries

2024-05-13 08:19 UTC, dtrucs commented on package.json
> +    "node-fetch": "^3.3.2",
Useful?

2024-11-04 17:03 UTC, dtrucs requested changes

2024-11-12 10:57 UTC, dtrucs commented on src/components/observation-cta.tsx
> +                    href={`/map/observation/${
```suggestion
                    key={observation.id}
                    href={`/map/observation/${
```

2025-02-06 17:12 UTC, Bo-Duke commented on src/components/observation-cta.tsx
> +    getObservations().then(res => setObservations(res));
Maybe we should open an issue for this if it's really needed?

2025-02-11 13:57 UTC, dtrucs approved these changes

2025-02-11 13:59 UTC, merged